Enable tests that rely on device malloc, remove kernel checks
ROCmSoftwarePlatform/rocThrust pull request #234
Opened 2022-05-12 12:41 UTC by nolmoonen

An upcoming ROCm version will fix device malloc. This PR removes checks compile checks that prevented using this functionality and enables tests that rely on device malloc.

2022-07-11 15:18 UTC, saadrahim requested changes
Please add a note to the changelog as well. Device Malloc support re-enablement is good news.

2022-07-11 16:37 UTC, saadrahim commented
Please wait for Stanley's review prior to merging.

2022-07-13 23:03 UTC, stanleytsang-amd commented
Compilation is failing on HIP on Windows with undefined references to malloc and free; Trying to confirm whether or not device malloc is enabled for Windows or if its just Linux.

2022-07-15 22:45 UTC, stanleytsang-amd reviewed
I'm told that device malloc *should* work on HIP on Windows, however CI seems to be struggling to compile the code.  On my local Windows dev machine I can get it to compile just fine, but when running the device malloc unit tests, I get hangs.

@nolmoonen I think we should temporarily disable compiling these tests on Windows for now while I get it sorted out with the Windows team.  Then we can merge this PR in and re-enable for Windows when fixed.

2022-07-18 15:14 UTC, merged