thrust::optional preserves trivially copyable
ROCmSoftwarePlatform/rocThrust pull request #373
Opened 2024-01-30 16:23 UTC by Naraenda

This PR fixes thrust::optional not being trivially copyable. It was added in thrust 2.2. An additional test has also been added for sanity's sake.

CC @stanleytsang-amd

2024-02-02 16:45 UTC, stanleytsang-amd requested changes

2024-02-02 16:45 UTC, stanleytsang-amd commented on CHANGELOG.md
> +## (Unreleased) rocThrust 3.x.x for ROCm 6.1
@Naraenda All tests pass. Given that the only change for ROCm 6.1 (so far) is this minor bugfix, can you update the rocThrust version to be 3.0.1?  And also in https://github.com/ROCm/rocThrust/blob/develop/CMakeLists.txt#L125.  Then we can merge this in.  Thanks!

2024-02-06 13:07 UTC, Naraenda commented on CHANGELOG.md
> +## (Unreleased) rocThrust 3.x.x for ROCm 6.1
Version bumped in da535c4

2024-02-06 20:11 UTC, stanleytsang-amd approved these changes

2024-02-06 20:12 UTC, merged