Add changelog entry about hipGraph support
ROCmSoftwarePlatform/rocThrust pull request #412
Opened 2024-05-30 19:17 UTC by umfranzw

Currently, we don't support calling rocThrust API function from within hipGraphs. 
Add a note to the changelog to indicate this.

2024-05-31 20:40 UTC, stanleytsang-amd requested changes
I think we should made a page in the documentation on this.  It'll be too easy for this information to get buried in the changelog after a few releases.

If the list isn't too large we could also list which functions do work with hipGraphs in that documentation page.

2024-06-04 19:50 UTC, umfranzw commented
Thanks Stanley, that makes a lot of sense. I'm just sorting out a few issues with the documentation build and then I'll add this in.

2024-06-12 12:40 UTC, umfranzw commented
I've added a documentation page on hipGraphs. You can view the formatted version in the readthedocs build for this PR here: https://advanced-micro-devices-demo--412.com.readthedocs.build/projects/rocThrust/en/412/
I was a little unsure about the level of detail that should be included in the explanation - feel free to let me know if you think it should be adjusted. Unfortunately, currently, there are no algorithms (not even the ones in the asynchronous API) that work inside of hipGraphs, so I haven't included a list.

2024-06-18 17:41 UTC, stanleytsang-amd approved these changes
New documentation looks great to me, I think that's a perfect level of detail.

2024-06-19 13:15 UTC, merged