[Extended Tests][rocThrust] Implemented extended tests filter for emulation work.
ROCmSoftwarePlatform/rocThrust pull request #487
Opened 2024-11-13 19:04 UTC by NguyenNhuDi

Implementation for extended tests for emulation work.

This PR is a continuation of the previous PR (#482) and (#485). Do not merge this PR until both (#482) and (#485) is closed and merged.

2024-11-13 19:28 UTC, spolifroni-amd requested changes
Header names need to be changed, but otherwise fine.

2024-11-13 19:28 UTC, spolifroni-amd commented on CHANGELOG.md
>  ### Additions
```suggestion
### Added
```

2024-11-13 19:28 UTC, spolifroni-amd commented on CHANGELOG.md
>  ### Changes
```suggestion
### Changed
```

2024-11-14 19:13 UTC, stanleytsang-amd approved these changes

2024-11-14 20:10 UTC, spolifroni-amd approved these changes

2024-11-14 20:12 UTC, merged